apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-proxy
  template:
    metadata:
      annotations:
        commit_sha: ${CI_SHA1}
      labels:
        app: mongodb-proxy
    spec:
      containers:
        - name: mongodb-proxy
          image: localhost:32000/mongodb-proxy:1.0.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-proxy
spec:
  type: LoadBalancer
  selector:
    app: mongodb-proxy
  ports:
    - port: 3000
      targetPort: 3000
